apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ include "dq.fullname" . }}-secret
  namespace: {{ .Release.Namespace }}
spec:
  data:
  - remoteRef:
      key: {{ .Release.Namespace }}/dq/secret-key
    secretKey: SECRET_KEY
  secretStoreRef:
    kind: ClusterSecretStore
    name: aws-secretsmanager-secret-store
  target:
    name: {{ include "dq.fullname" . }}-secret
    template:
      metadata: {}
