package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.87

import (
	"context"
	"time"

	"github.com/99designs/gqlgen/graphql"
	"github.com/DIMO-Network/dq/internal/graph/model"
	"github.com/DIMO-Network/dq/internal/repositories"
)

// Signals is the resolver for the signals field.
func (r *queryResolver) Signals(ctx context.Context, did string, interval string, from time.Time, to time.Time, filter *model.SignalFilter) ([]*model.SignalAggregations, error) {
	aggArgs, err := aggregationArgsFromContext(ctx, did, interval, from, to, filter)
	if err != nil {
		return nil, err
	}
	return r.SignalRepo.GetSignal(ctx, aggArgs)
}

// SignalsLatest is the resolver for the signalsLatest field.
func (r *queryResolver) SignalsLatest(ctx context.Context, did string, filter *model.SignalFilter) (*model.SignalCollection, error) {
	latestArgs, err := latestArgsFromContext(ctx, did, filter)
	if err != nil {
		return nil, err
	}
	return r.SignalRepo.GetSignalLatest(ctx, latestArgs)
}

// AvailableSignals is the resolver for the availableSignals field.
func (r *queryResolver) AvailableSignals(ctx context.Context, did string, filter *model.SignalFilter) ([]string, error) {
	return r.SignalRepo.GetAvailableSignals(ctx, did, filter)
}

// DataSummary is the resolver for the dataSummary field.
func (r *queryResolver) DataSummary(ctx context.Context, did string, filter *model.SignalFilter) (*model.DataSummary, error) {
	return r.SignalRepo.GetDataSummary(ctx, did, filter)
}

// CurrentLocationApproximateCoordinates is the resolver for the currentLocationApproximateCoordinates field.
func (r *signalAggregationsResolver) CurrentLocationApproximateCoordinates(ctx context.Context, obj *model.SignalAggregations, agg model.LocationAggregation) (*model.Location, error) {
	fieldCtx := graphql.GetFieldContext(ctx)
	vl, ok := obj.ValueLocations[fieldCtx.Field.Alias]
	if !ok {
		return nil, nil
	}
	latLng := repositories.GetApproximateLoc(vl.Latitude, vl.Longitude)
	if latLng == nil {
		return nil, nil
	}
	return &model.Location{Latitude: latLng.Lat, Longitude: latLng.Lng, Hdop: vl.HDOP}, nil
}

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

// SignalAggregations returns SignalAggregationsResolver implementation.
func (r *Resolver) SignalAggregations() SignalAggregationsResolver {
	return &signalAggregationsResolver{r}
}

type queryResolver struct{ *Resolver }
type signalAggregationsResolver struct{ *Resolver }
