package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.89

import (
	"context"
	"errors"
	"time"

	"github.com/99designs/gqlgen/graphql"
	"github.com/DIMO-Network/dq/internal/coverage"
	"github.com/DIMO-Network/dq/internal/graph/model"
	"github.com/DIMO-Network/dq/internal/repositories"
	"github.com/DIMO-Network/server-garage/pkg/gql/errorhandler"
)

// Signals is the resolver for the signals field.
func (r *queryResolver) Signals(ctx context.Context, subject string, interval string, from time.Time, to time.Time, filter *model.SignalFilter) ([]*model.SignalAggregations, error) {
	aggArgs, err := aggregationArgsFromContext(ctx, subject, interval, from, to, filter)
	if err != nil {
		return nil, err
	}
	return r.SignalRepo.GetSignal(ctx, aggArgs)
}

// SignalsLatest is the resolver for the signalsLatest field.
func (r *queryResolver) SignalsLatest(ctx context.Context, subject string, filter *model.SignalFilter) (*model.SignalCollection, error) {
	latestArgs, err := latestArgsFromContext(ctx, subject, filter)
	if err != nil {
		return nil, err
	}
	return r.SignalRepo.GetSignalLatest(ctx, latestArgs)
}

// AvailableSignals is the resolver for the availableSignals field.
func (r *queryResolver) AvailableSignals(ctx context.Context, subject string, filter *model.SignalFilter) ([]string, error) {
	names, err := r.SignalRepo.GetAvailableSignals(ctx, subject, filter)
	if err != nil {
		return nil, err
	}
	// Don't reveal the EXISTENCE of location (or other privileged) signals to a caller
	// lacking the privilege — gate the name list the same way signalsSnapshot gates values
	// (a VEHICLE_NON_LOCATION_DATA-only token would otherwise see currentLocationCoordinates
	// in the list, leaking that the vehicle has location data).
	holds := abilitiesFromCtx(ctx, subject)
	out := names[:0]
	for _, n := range names {
		if hasPrivilegesForSignal(r.SignalRepo, n, holds) {
			out = append(out, n)
		}
	}
	return out, nil
}

// DataSummary is the resolver for the dataSummary field.
func (r *queryResolver) DataSummary(ctx context.Context, subject string, filter *model.SignalFilter) (*model.DataSummary, error) {
	// The summary's counts and first/last-seen times are over all of the
	// subject's data, and are read from rollups that cannot be bounded by a
	// window. A token whose windows do not cover all time would learn from it
	// how much data exists outside them and when, so it is refused; such a
	// caller asks signals over a range instead.
	if !coverage.Unbounded(ctx) {
		return nil, errorhandler.NewUnauthorizedError(ctx, errors.New("dataSummary covers all of a vehicle's data; this token's windows do not, so query signals over a range instead"))
	}
	summary, err := r.SignalRepo.GetDataSummary(ctx, subject, filter)
	if err != nil {
		return nil, err
	}
	// Same leak as availableSignals: the per-signal summary exposes the count + first/last-
	// seen of every signal, including location, without the privilege. Filter the name list
	// + per-signal summaries and recompute the aggregate count so it doesn't reveal the
	// location data-point count either.
	holds := abilitiesFromCtx(ctx, subject)
	names := summary.AvailableSignals[:0]
	for _, n := range summary.AvailableSignals {
		if hasPrivilegesForSignal(r.SignalRepo, n, holds) {
			names = append(names, n)
		}
	}
	summary.AvailableSignals = names
	var total uint64
	sds := summary.SignalDataSummary[:0]
	for _, s := range summary.SignalDataSummary {
		if hasPrivilegesForSignal(r.SignalRepo, s.Name, holds) {
			sds = append(sds, s)
			total += s.NumberOfSignals
		}
	}
	summary.SignalDataSummary = sds
	summary.NumberOfSignals = total
	return summary, nil
}

// SignalsSnapshot is the resolver for the signalsSnapshot field.
func (r *queryResolver) SignalsSnapshot(ctx context.Context, subject string, filter *model.SignalFilter) (*model.SignalsSnapshotResponse, error) {
	resp, err := r.SignalRepo.GetSignalSnapshot(ctx, subject, filter)
	if err != nil {
		return nil, err
	}
	holds := abilitiesFromCtx(ctx, subject)
	filtered := make([]*model.LatestSignal, 0, len(resp.Signals))
	for _, sig := range resp.Signals {
		if hasPrivilegesForSignal(r.SignalRepo, sig.Name, holds) {
			filtered = append(filtered, sig)
		}
	}
	resp.Signals = filtered
	return resp, nil
}

// CurrentLocationApproximateCoordinates is the resolver for the currentLocationApproximateCoordinates field.
func (r *signalAggregationsResolver) CurrentLocationApproximateCoordinates(ctx context.Context, obj *model.SignalAggregations, agg model.LocationAggregation) (*model.Location, error) {
	fieldCtx := graphql.GetFieldContext(ctx)
	vl, ok := obj.ValueLocations[fieldCtx.Field.Alias]
	if !ok {
		return nil, nil
	}
	latLng := repositories.GetApproximateLoc(vl.Latitude, vl.Longitude)
	if latLng == nil {
		return nil, nil
	}
	return &model.Location{Latitude: latLng.Lat, Longitude: latLng.Lng, Hdop: vl.HDOP}, nil
}

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

// SignalAggregations returns SignalAggregationsResolver implementation.
func (r *Resolver) SignalAggregations() SignalAggregationsResolver {
	return &signalAggregationsResolver{r}
}

type queryResolver struct{ *Resolver }
type signalAggregationsResolver struct{ *Resolver }
