package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.87

import (
	"context"
	"database/sql"
	"errors"
	"fmt"
	"slices"
	"strings"

	"github.com/DIMO-Network/cloudevent"
	"github.com/DIMO-Network/dq/internal/fetch"
	"github.com/DIMO-Network/dq/internal/graph/model"
	"github.com/DIMO-Network/dq/pkg/eventrepo"
	"github.com/DIMO-Network/fetch-api/pkg/grpc"
	"github.com/DIMO-Network/token-exchange-api/pkg/tokenclaims"
)

const (
	errNoTokenClaims     = "unauthorized: no token claims"
	errNoPermission      = "unauthorized: token does not have required permission for this operation"
	errNoAccessToSubject = "unauthorized: token does not have access to this subject"
)

// Header is the resolver for the header field.
func (r *cloudEventResolver) Header(ctx context.Context, obj *CloudEventWrapper) (*cloudevent.CloudEventHeader, error) {
	if obj == nil || obj.Raw == nil {
		return nil, nil
	}
	return &obj.Raw.CloudEventHeader, nil
}

// Data is the resolver for the data field.
func (r *cloudEventResolver) Data(ctx context.Context, obj *CloudEventWrapper) (RawJSON, error) {
	if obj == nil || obj.Raw == nil || len(obj.Raw.Data) == 0 {
		return nil, nil
	}
	return RawJSON(obj.Raw.Data), nil
}

// DataBase64 is the resolver for the dataBase64 field.
func (r *cloudEventResolver) DataBase64(ctx context.Context, obj *CloudEventWrapper) (*string, error) {
	if obj == nil || obj.Raw == nil || obj.Raw.DataBase64 == "" {
		return nil, nil
	}
	return &obj.Raw.DataBase64, nil
}

// LatestCloudEvent is the resolver for the latestCloudEvent field.
func (r *queryResolver) LatestCloudEvent(ctx context.Context, did string, filter *model.CloudEventFilter) (*CloudEventWrapper, error) {
	opts, err := r.requireSubjectOptsByDID(ctx, did, filter)
	if err != nil {
		return nil, err
	}
	idx, err := r.EventService.GetLatestIndexAdvanced(ctx, opts)
	if err != nil {
		return nil, err
	}
	if strings.HasPrefix(idx.Data.Key, eventrepo.BlobKeyPrefix) {
		url, err := r.EventService.PresignBlobURL(ctx, idx.Data.Key)
		if err != nil {
			return nil, err
		}
		hdr := idx.CloudEventHeader
		return &CloudEventWrapper{Raw: &cloudevent.RawEvent{CloudEventHeader: hdr}, DataURL: url}, nil
	}
	ce, err := fetch.GetCloudEventFromIndex(ctx, r.EventService, &idx, r.Buckets)
	if err != nil {
		return nil, err
	}
	return &CloudEventWrapper{Raw: &ce}, nil
}

// CloudEvents is the resolver for the cloudEvents field.
func (r *queryResolver) CloudEvents(ctx context.Context, did string, limit *int, filter *model.CloudEventFilter) ([]*CloudEventWrapper, error) {
	opts, err := r.requireSubjectOptsByDID(ctx, did, filter)
	if err != nil {
		return nil, err
	}
	list, err := r.EventService.ListIndexesAdvanced(ctx, resolveLimit(limit), opts)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return emptyCloudEventList, nil
		}
		return nil, err
	}

	out := make([]*CloudEventWrapper, len(list))
	var nonBlobIdxs []cloudevent.CloudEvent[eventrepo.ObjectInfo]
	var nonBlobPos []int

	for i, idx := range list {
		if strings.HasPrefix(idx.Data.Key, eventrepo.BlobKeyPrefix) {
			url, err := r.EventService.PresignBlobURL(ctx, idx.Data.Key)
			if err != nil {
				return nil, err
			}
			hdr := idx.CloudEventHeader
			out[i] = &CloudEventWrapper{Raw: &cloudevent.RawEvent{CloudEventHeader: hdr}, DataURL: url}
		} else {
			nonBlobIdxs = append(nonBlobIdxs, idx)
			nonBlobPos = append(nonBlobPos, i)
		}
	}

	if len(nonBlobIdxs) > 0 {
		events, err := fetch.ListCloudEventsFromIndexes(ctx, r.EventService, nonBlobIdxs, r.Buckets)
		if err != nil {
			return nil, err
		}
		for j := range events {
			ev := events[j]
			out[nonBlobPos[j]] = &CloudEventWrapper{Raw: &ev}
		}
	}

	return out, nil
}

// AvailableCloudEventTypes is the resolver for the availableCloudEventTypes field.
func (r *queryResolver) AvailableCloudEventTypes(ctx context.Context, did string, filter *model.CloudEventFilter) ([]*model.CloudEventTypeSummary, error) {
	opts, err := r.requireSubjectOptsByDID(ctx, did, filter)
	if err != nil {
		return nil, err
	}
	summaries, err := r.EventService.GetCloudEventTypeSummariesAdvanced(ctx, opts)
	if err != nil {
		return nil, err
	}
	out := make([]*model.CloudEventTypeSummary, len(summaries))
	for i, s := range summaries {
		out[i] = &model.CloudEventTypeSummary{
			Type:      s.Type,
			Count:     int(s.Count),
			FirstSeen: s.FirstSeen,
			LastSeen:  s.LastSeen,
		}
	}
	return out, nil
}

// requireSubjectOptsByDID validates raw-data access and returns advanced search options for the DID.
func (r *queryResolver) requireSubjectOptsByDID(ctx context.Context, requestedDID string, filter *model.CloudEventFilter) (*grpc.AdvancedSearchOptions, error) {
	token, err := requireRawDataToken(ctx)
	if err != nil {
		return nil, err
	}
	tokenSubjectDID := token.Asset
	searchSubject, err := r.ensureRequestedDIDLinkedToPermissionedSubject(ctx, requestedDID, tokenSubjectDID)
	if err != nil {
		return nil, err
	}
	return filterToAdvancedSearchOptions(filter, searchSubject), nil
}

// requireRawDataToken returns the token if the context has claims and the token has raw-data permission.
func requireRawDataToken(ctx context.Context) (*tokenclaims.Token, error) {
	tok, _ := ctx.Value(ClaimsContextKey{}).(*tokenclaims.Token)
	if tok == nil {
		return nil, fmt.Errorf("%s", errNoTokenClaims)
	}
	hasGetRawData := slices.Contains(tok.Permissions, tokenclaims.PermissionGetRawData)
	hasLocationHistory := slices.Contains(tok.Permissions, tokenclaims.PermissionGetLocationHistory)
	hasNonLocationHistory := slices.Contains(tok.Permissions, tokenclaims.PermissionGetNonLocationHistory)
	hasAllTimeData := hasLocationHistory && hasNonLocationHistory
	if !hasGetRawData && !hasAllTimeData {
		return nil, fmt.Errorf("%s", errNoPermission)
	}
	return tok, nil
}

// ensureRequestedDIDLinkedToPermissionedSubject verifies the client-requested DID is allowed by the token.
func (r *queryResolver) ensureRequestedDIDLinkedToPermissionedSubject(ctx context.Context, requestedDID string, tokenSubjectDID string) (string, error) {
	if requestedDID == tokenSubjectDID {
		return requestedDID, nil
	}
	requestedDIDParsed, err := cloudevent.DecodeERC721DID(requestedDID)
	if err != nil {
		return "", fmt.Errorf("%s", errNoAccessToSubject)
	}
	if r.IdentityClient == nil {
		return "", fmt.Errorf("%s", errNoAccessToSubject)
	}
	linkedDID, err := r.IdentityClient.GetLinkedDIDForDevice(ctx, requestedDIDParsed.String())
	if err != nil || linkedDID != tokenSubjectDID {
		return "", fmt.Errorf("%s", errNoAccessToSubject)
	}
	return requestedDIDParsed.String(), nil
}

// CloudEvent returns CloudEventResolver implementation.
func (r *Resolver) CloudEvent() CloudEventResolver { return &cloudEventResolver{r} }

type cloudEventResolver struct{ *Resolver }
