package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.89

import (
	"context"
	"database/sql"
	"errors"
	"strings"

	"github.com/DIMO-Network/cloudevent"
	"github.com/DIMO-Network/dq/internal/fetch"
	"github.com/DIMO-Network/dq/internal/graph/model"
	"github.com/DIMO-Network/dq/pkg/eventrepo"
)

// Header is the resolver for the header field.
func (r *cloudEventResolver) Header(ctx context.Context, obj *CloudEventWrapper) (*cloudevent.CloudEventHeader, error) {
	if obj == nil || obj.Raw == nil {
		return nil, nil
	}
	return &obj.Raw.CloudEventHeader, nil
}

// Data is the resolver for the data field.
func (r *cloudEventResolver) Data(ctx context.Context, obj *CloudEventWrapper) (RawJSON, error) {
	if obj == nil || obj.Raw == nil || len(obj.Raw.Data) == 0 {
		return nil, nil
	}
	return RawJSON(obj.Raw.Data), nil
}

// DataBase64 is the resolver for the dataBase64 field.
func (r *cloudEventResolver) DataBase64(ctx context.Context, obj *CloudEventWrapper) (*string, error) {
	if obj == nil || obj.Raw == nil || obj.Raw.DataBase64 == "" {
		return nil, nil
	}
	return &obj.Raw.DataBase64, nil
}

// LatestCloudEvent is the resolver for the latestCloudEvent field.
func (r *queryResolver) LatestCloudEvent(ctx context.Context, subject string, filter *model.CloudEventFilter) (*CloudEventWrapper, error) {
	opts, err := r.requireSubjectOptsByDID(ctx, subject, filter)
	if err != nil {
		return nil, err
	}
	idx, err := r.EventService.GetLatestIndexAdvanced(ctx, opts)
	if err != nil {
		return nil, err
	}
	hdr := idx.CloudEventHeader
	if strings.HasPrefix(idx.Data.Key, eventrepo.BlobKeyPrefix) {
		url, err := r.EventService.PresignBlobURL(ctx, idx.Data.Key)
		if err != nil {
			return nil, err
		}
		return &CloudEventWrapper{Raw: &cloudevent.RawEvent{CloudEventHeader: hdr}, DataURL: url}, nil
	}
	if !dataFieldsRequested(ctx) {
		return &CloudEventWrapper{Raw: &cloudevent.RawEvent{CloudEventHeader: hdr}}, nil
	}
	ce, err := fetch.GetCloudEventFromIndex(ctx, r.EventService, &idx, r.Buckets)
	if err != nil {
		return nil, err
	}
	return &CloudEventWrapper{Raw: &ce}, nil
}

// CloudEvents is the resolver for the cloudEvents field.
func (r *queryResolver) CloudEvents(ctx context.Context, subject string, limit *int, filter *model.CloudEventFilter) ([]*CloudEventWrapper, error) {
	opts, err := r.requireSubjectOptsByDID(ctx, subject, filter)
	if err != nil {
		return nil, err
	}
	list, err := r.EventService.ListIndexesAdvanced(ctx, resolveLimit(limit), opts)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return emptyCloudEventList, nil
		}
		return nil, err
	}

	out := make([]*CloudEventWrapper, len(list))
	var nonBlobIdxs []cloudevent.CloudEvent[eventrepo.ObjectInfo]
	var nonBlobPos []int
	fetchData := dataFieldsRequested(ctx)

	for i, idx := range list {
		hdr := idx.CloudEventHeader
		if strings.HasPrefix(idx.Data.Key, eventrepo.BlobKeyPrefix) {
			url, err := r.EventService.PresignBlobURL(ctx, idx.Data.Key)
			if err != nil {
				return nil, err
			}
			out[i] = &CloudEventWrapper{Raw: &cloudevent.RawEvent{CloudEventHeader: hdr}, DataURL: url}
		} else if fetchData {
			nonBlobIdxs = append(nonBlobIdxs, idx)
			nonBlobPos = append(nonBlobPos, i)
		} else {
			out[i] = &CloudEventWrapper{Raw: &cloudevent.RawEvent{CloudEventHeader: hdr}}
		}
	}

	if len(nonBlobIdxs) > 0 {
		events, err := fetch.ListCloudEventsFromIndexes(ctx, r.EventService, nonBlobIdxs, r.Buckets)
		if err != nil {
			return nil, err
		}
		for j := range events {
			ev := events[j]
			out[nonBlobPos[j]] = &CloudEventWrapper{Raw: &ev}
		}
	}

	return out, nil
}

// AvailableCloudEventTypes is the resolver for the availableCloudEventTypes field.
func (r *queryResolver) AvailableCloudEventTypes(ctx context.Context, subject string, filter *model.CloudEventFilter) ([]*model.CloudEventTypeSummary, error) {
	opts, err := r.requireSubjectOptsByDID(ctx, subject, filter)
	if err != nil {
		return nil, err
	}
	summaries, err := r.EventService.GetCloudEventTypeSummariesAdvanced(ctx, opts)
	if err != nil {
		return nil, err
	}
	out := make([]*model.CloudEventTypeSummary, len(summaries))
	for i, s := range summaries {
		out[i] = &model.CloudEventTypeSummary{
			Type:      s.Type,
			Count:     int(s.Count),
			FirstSeen: s.FirstSeen,
			LastSeen:  s.LastSeen,
		}
	}
	return out, nil
}

// CloudEvent returns CloudEventResolver implementation.
func (r *Resolver) CloudEvent() CloudEventResolver { return &cloudEventResolver{r} }

type cloudEventResolver struct{ *Resolver }
