package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.89

import (
	"context"
	"time"

	"github.com/DIMO-Network/dq/internal/graph/model"
)

// Events is the resolver for the events field.
func (r *queryResolver) Events(ctx context.Context, did string, from time.Time, to time.Time, filter *model.EventFilter) ([]*model.Event, error) {
	return r.SignalRepo.GetEvents(ctx, did, from, to, filter)
}
